export const GAME_SCENE_MAP: Record<string, string> = {
    catcher: 'GameScene',
    breakout: 'BreakoutGameScene',
    tetris: 'TetrisGameScene',
    invaders: 'InvadersGameScene',
    pong: 'PongGameScene',
    snake: 'SnakeGameScene',
    flappy: 'FlappyGameScene',
    asteroid: 'AsteroidGameScene',
    balloonpop: 'BalloonPopGameScene',
    memorytiles: 'MemoryTilesGameScene',
    frogger: 'FroggerGameScene',
    catchmonsters: 'CatchMonstersGameScene',
    whackmole: 'WhackMoleGameScene',
    game2048: 'Game2048Scene',
    knifehit: 'KnifeHitGameScene',
    runner: 'RunnerGameScene',
    colorflood: 'ColorFloodGameScene',
    match3: 'Match3GameScene',
    slidingpuzzle: 'SlidingPuzzleGameScene',
    pacman: 'PacmanGameScene',
};

export const START_EVENT_MAP: Record<string, string> = {
    catcher: 'start-game',
    breakout: 'start-breakout-game',
    tetris: 'start-tetris-game',
    invaders: 'start-invaders-game',
    pong: 'start-pong-game',
    snake: 'start-snake-game',
    flappy: 'start-flappy-game',
    asteroid: 'start-asteroid-game',
    balloonpop: 'start-balloonpop-game',
    memorytiles: 'start-memorytiles-game',
    frogger: 'start-frogger-game',
    catchmonsters: 'start-catchmonsters-game',
    whackmole: 'start-whackmole-game',
    game2048: 'start-game2048-game',
    knifehit: 'start-knifehit-game',
    runner: 'start-runner-game',
    colorflood: 'start-colorflood-game',
    match3: 'start-match3-game',
    slidingpuzzle: 'start-slidingpuzzle-game',
    pacman: 'start-pacman-game',
};
